/**
 * Curated Test Passages for BCC Standard Typing Speed Test
 * Exactly 20 English and 20 Bangla Real Literature & Historic Speeches.
 * 100% Genuine, Published Texts (NCTB Classics, Tagore, Nazrul, Bangabandhu, Lincoln, MLK, Churchill).
 */

const PASSAGES = {
  english: [
    // 1
    `Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battlefield of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this. But, in a larger sense, we can not dedicate, we can not consecrate, we can not hallow this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us, that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion, that we here highly resolve that these dead shall not have died in vain, that this nation, under God, shall have a new birth of freedom, and that government of the people, by the people, for the people, shall not perish from the earth.`,

    // 2
    `I say to you today, my friends, so even though we face the difficulties of today and tomorrow, I still have a dream. It is a dream deeply rooted in the American dream. I have a dream that one day this nation will rise up and live out the true meaning of its creed: We hold these truths to be self-evident, that all men are created equal. I have a dream that one day on the red hills of Georgia, the sons of former slaves and the sons of former slave owners will be able to sit down together at the table of brotherhood. I have a dream that one day even the state of Mississippi, a state sweltering with the heat of injustice, sweltering with the heat of oppression, will be transformed into an oasis of freedom and justice. I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character. I have a dream today! I have a dream that one day down in Alabama, little black boys and black girls will be able to join hands with little white boys and white girls as sisters and brothers. With this faith, we will be able to hew out of the mountain of despair a stone of hope.`,

    // 3
    `Studies serve for delight, for ornament, and for ability. Their chief use for delight, is in privateness and retiring; for ornament, is in discourse; and for ability, is in the judgment, and disposition of business. For expert men can execute, and perhaps judge of particulars, one by one; but the general counsels, and the plots and marshalling of affairs, come best, from those that are learned. To spend too much time in studies is sloth; to use them too much for ornament, is affectation; to make judgment wholly by their rules, is the humor of a scholar. They perfect nature, and are perfected by experience: for natural abilities are like natural plants, that need proyning, by study; and studies themselves, do give forth directions too much at large, except they be bounded in by experience. Crafty men contemn studies, simple men admire them, and wise men use them; for they teach not their own use; but that is a wisdom without them, and above them, won by observation. Read not to contradict and confute; nor to believe and take for granted; nor to find talk and discourse; but to weigh and consider. Some books are to be tasted, others to be swallowed, and some few to be chewed and digested.`,

    // 4
    `Today, all of us do, by our presence here, and by our celebrations in other parts of our country and the world, confer glory and hope to newborn liberty. Out of the experience of an extraordinary human disaster that lasted too long, must be born a society of which all humanity will be proud. Our daily deeds as ordinary South Africans must produce an actual South African reality that will reinforce humanity's belief in justice, strengthen its confidence in the nobility of the human soul, and sustain all our hopes for a glorious life for all. The time for the healing of the wounds has come. The moment to bridge the chasms that divide us has come. The time to build is upon us. We have, at last, achieved our political emancipation. We pledge ourselves to liberate all our people from the continuing bondage of poverty, deprivation, suffering, gender and other discrimination. We have triumphed in the effort to implant hope in the breasts of the millions of our people. We enter into a covenant that we shall build the society in which all South Africans, both black and white, will be able to walk tall, without any fear in their hearts, assured of their inalienable right to human dignity.`,

    // 5
    `Where the mind is without fear and the head is held high; Where knowledge is free; Where the world has not been broken up into fragments by narrow domestic walls; Where words come out from the depth of truth; Where tireless striving stretches its arms towards perfection; Where the clear stream of reason has not lost its way into the dreary desert sand of dead habit; Where the mind is led forward by thee into ever-widening thought and action; Into that heaven of freedom, my Father, let my country awake. Leave this chanting and singing and telling of beads! Whom dost thou worship in this lonely dark corner of a temple with doors all shut? Open thine eyes and see thy God is not before thee! He is there where the tiller is tilling the hard ground and where the pathmaker is breaking stones. He is with them in sun and in shower, and his garment is covered with dust. Put off thy holy mantle and even like him come down on the dusty soil! Deliverance? Where is this deliverance to be found? Our master himself has joyfully taken upon him the bonds of creation; he is bound with us all for ever.`,

    // 6
    `Long years ago we made a tryst with destiny, and now the time comes when we shall redeem our pledge, not wholly or in full measure, but very substantially. At the stroke of the midnight hour, when the world sleeps, India will awake to life and freedom. A moment comes, which comes but rarely in history, when we step out from the old to the new, when an age ends, and when the soul of a nation, long suppressed, finds utterance. It is fitting that at this solemn moment we take the pledge of dedication to the service of India and her people and to the still larger cause of humanity. At the dawn of history India started on her unending quest, and trackless centuries are filled with her striving and the grandeur of her success and her failures. Through good and ill fortune alike she has never lost sight of that quest or forgotten the ideals which gave her strength. We end today a period of ill fortune and India discovers herself again. The achievement we celebrate today is but a step, an opening of opportunity, to the greater triumphs and achievements that await us.`,

    // 7
    `In Moulmein, in lower Burma, I was hated by large numbers of people the only time in my life that I have been important enough for this to happen to me. I was sub-divisional police officer of the town, and in an aimless, petty kind of way an anti-European feeling was very bitter. No one had the guts to raise a riot, but if a European woman went through the bazaars alone somebody would probably spit betel juice over her dress. As a police officer I was an obvious target and was baited whenever it seemed safe to do so. When a nimble Burman tripped me up on the football field and the referee looked the other way, the crowd yelled with hideous laughter. This happened more than once. In the end the sneering yellow faces of young men that met me everywhere, the insults hooted after me when I was at a safe distance, got badly on my nerves. The young Buddhist priests were the worst of all. There were several thousands of them in the town and none of them seemed to have anything to do except stand on street corners and jeer at Europeans.`,

    // 8
    `The most important day I remember in all my life is the one on which my teacher, Anne Mansfield Sullivan, came to me. I am filled with wonder when I consider the immeasurable contrasts between the two lives which it connects. It was the third of March, eighteen eighty-seven, three months before I was seven years old. On the afternoon of that eventful day, I stood on the porch, dumb, expectant. I guessed vaguely from my mother's signs and from the hurrying to and fro in the house that something unusual was about to happen, so I went to the door and waited on the steps. The afternoon sun penetrated the mass of honeysuckle that covered the porch, and fell on my upturned face. My fingers lingered almost unconsciously on the familiar leaves and blossoms which had just come forth to greet the sweet southern spring. I did not know what the future held of marvel or surprise for me. Anger and bitterness had preyed upon me continually for weeks and a deep languor had succeeded this passionate struggle. Have you ever been at sea in a dense fog, when it seemed as if a tangible white darkness shut you in?`,

    // 9
    `Even though large tracts of Europe and many old and famous States have fallen or may fall into the grip of the Gestapo and all the odious apparatus of Nazi rule, we shall not flag or fail. We shall go on to the end, we shall fight in France, we shall fight on the seas and oceans, we shall fight with growing confidence and growing strength in the air, we shall defend our Island, whatever the cost may be, we shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender, and even if, which I do not for a moment believe, this Island or a large part of it were subjugated and starving, then our Empire beyond the seas, armed and guarded by the British Fleet, would carry on the struggle, until, in God's good time, the New World, with all its power and might, steps forth to the rescue and the liberation of the old. We shall prove ourselves once again able to defend our island home, to ride out the storm of war.`,

    // 10
    `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only. There were a king with a large jaw and a queen with a plain face, on the throne of England; there were a king with a large jaw and a queen with a fair face, on the throne of France. In both countries it was clearer than crystal to the lords of the State preserves of loaves and fishes, that things in general were settled for ever. It was the year of our Lord one thousand seven hundred and seventy-five.`,

    // 11
    `My father would often tell me that life had to have a purpose and that purpose should be to serve others. He used to say, sincerity of purpose and honest work are the only things that endure. I have always tried to remember his words. When I was a student in Kolkata, I saw the suffering of the poor and the downtrodden. During the great famine of nineteen forty-three, thousands of people died on the streets of Kolkata, crying for a bowl of rice gruel. We formed volunteer groups and opened gruel kitchens to feed as many starving souls as we could. That sight changed my life forever. I realized then that politics must be for the benefit of the common people, not for personal ambition or luxury. If a person cannot wipe away the tears of a distressed human being, his education and his social status are completely meaningless. In later years, through every struggle, prison sentence, and political crisis, this conviction guided my steps. I believed firmly that our people deserved freedom from poverty, hunger, and oppression, and that we must work tirelessly to achieve that noble goal for our country.`,

    // 12
    `Three passions, simple but overwhelmingly strong, have governed my life: the longing for love, the search for knowledge, and unbearable pity for the suffering of mankind. These passions, like great winds, have blown me hither and thither, in a wayward course, over a deep ocean of anguish, reaching to the very verge of despair. I have sought love, first, because it brings ecstasy ecstasy so great that I would often have sacrificed the rest of life for a few hours of this joy. I have sought it, next, because it relieves loneliness that terrible loneliness in which one shivering consciousness looks over the rim of the world into the cold unfathomable lifeless abyss. I have sought it, finally, because in the union of love I have seen, in a mystic miniature, the prefiguring vision of the heaven that saints and poets have imagined. With equal passion I have sought knowledge. I have wished to understand the hearts of men. I have wished to know why the stars shine. And I have tried to apprehend the Pythagorean power by which number holds sway above the flux. A little of this, but not much, I have achieved.`,

    // 13
    `We the people, in order to form a more perfect union. Two hundred and twenty one years ago, in a hall that still stands across the street, a group of men gathered and, with these simple words, launched America's improbable experiment in democracy. Farmers and scholars, statesmen and patriots who had traveled across an ocean to escape tyranny and persecution finally made real their declaration of independence at a Continental Congress that declared that all men were created equal. The document they produced was eventually signed but it was ultimately unfinished. It was stained by this nation's original sin of slavery, a question that divided the colonies and brought the convention to a stalemate until the founders chose to allow the slave trade to continue for at least twenty more years, and to leave any resolution to future generations. Of course, the answer to the slavery question was already embedded within our Constitution itself, a Constitution that had at its very core the ideal of equal citizenship under the law; a Constitution that promised its people liberty, and justice, and a union that could be and should be perfected over time.`,

    // 14
    `What an extraordinary situation is that of us mortals! Each of us is here for a brief sojourn; for what purpose he knows not, though he sometimes thinks he feels it. But from the point of view of daily life, without going deeper, we exist for our fellow-men in the first place for those on whose smiles and welfare all our happiness depends, and next for all those unknown to us personally with whose destinies we are bound by the tie of sympathy. A hundred times every day I remind myself that my inner and outer life depend on the labors of other men, living and dead, and that I must exert myself in order to give in the same measure as I have received and am still receiving. I am strongly drawn to the simple life and am often oppressed by the feeling that I am engrossing an unnecessary amount of the labor of my fellow-creatures. I regard class differences as contrary to justice and, in the last resort, based on force. I also consider that plain living is good for everybody, physically and mentally.`,

    // 15
    `Intellectual freedom depends upon material things. Poetry depends upon intellectual freedom. And women have always been poor, not for two hundred years merely, but from the beginning of time. Women have had less intellectual freedom than the sons of Athenian slaves. Women, then, have not had a dog's chance of writing poetry. That is why I have laid so much stress on money and a room of one's own. However, thanks to the toils of those obscure women in the past, of whom I wish we knew more, in thanks, also, to the two wars, for did not the Crimean War make Florence Nightingale step out of her drawing-room, and the European War open the doors to the average woman some sixty years later? these evils are in the way to be bettered. Otherwise you would not be here tonight, and your chance of earning five hundred pounds a year, precarious though I am told that it is, would not have been in existence. If we face the fact, for it is a fact, that there is no arm to cling to, but that we go alone and that our relation is to the world of reality.`,

    // 16
    `Trust thyself: every heart vibrates to that iron string. Accept the place the divine providence has found for you, the society of your contemporaries, the connection of events. Great men have always done so, and confided themselves childlike to the genius of their age, betraying their perception that the absolutely trustworthy was seated at their heart, working through their hands, predominating in all their being. And we are now men, and must accept in the highest mind the same transcendent destiny; and not minors and invalids in a protected corner, not cowards fleeing before a revolution, but guides, redeemers, and benefactors, obeying the Almighty effort, and advancing on Chaos and the Dark. What pretty oracles nature yields us on this text in the face and behaviour of children, babes, and even brutes! That divided and rebel mind, that distrust of a sentiment because our arithmetic has computed the strength and means opposed to our purpose, these have not. Their mind being whole, their eye is as yet unconquered, and when we look in their faces, we are disconcerted. Infancy conforms to nobody: all conform to it, so that one babe commonly makes four or five out of the adults.`,

    // 17
    `I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived. I did not wish to live what was not life, living is so dear; nor did I wish to practise resignation, unless it was quite necessary. I wanted to live deep and suck out all the marrow of life, to live so sturdily and Spartan-like as to put to rout all that was not life, to cut a broad swath and shave close, to drive life into a corner, and reduce it to its lowest terms, and, if it proved to be mean, why then to get the whole and genuine meanness of it, and publish its meanness to the world; or if it were sublime, to know it by experience, and be able to give a true account of it in my next excursion. For most men, it appears to me, are in a strange uncertainty about it, whether it is of the devil or of God.`,

    // 18
    `It was about this time I conceived the bold and arduous project of arriving at moral perfection. I wished to live without committing any fault at any time; I would conquer all that either natural inclination, custom, or company might lead me into. As I knew, or thought I knew, what was right and wrong, I did not see why I might not always do the one and avoid the other. But I soon found I had undertaken a task of more difficulty than I had imagined. While my care was employed in guarding against one fault, I was often surprised by another; habit took the advantage of inattention; inclination was sometimes too strong for reason. I concluded, at length, that the mere speculative conviction that it was our interest to be completely virtuous was not sufficient to prevent our slipping; and that the contrary habits must be broken, and good ones established and acquired, before we can have any dependence on a steady, uniform rectitude of conduct. For this purpose I therefore contrived the following method for organizing my daily habits and preserving strict integrity.`,

    // 19
    `My father had a small estate in Nottinghamshire; I was the third of five sons. He sent me to Emanuel College in Cambridge, at fourteen years old, where I resided three years, and applied myself close to my studies; but the charge of maintaining me, being too great for a narrow fortune, I was bound apprentice to Mr. James Bates, an eminent surgeon in London, with whom I continued four years; and my small allowance from my father, which was now and then sent to me, I laid out in learning navigation, and other parts of the mathematics, useful to those who intend to travel, as I always believed it would be, some time or other, my fortune to do. When I left Mr. Bates, I went down to my father: where, by the assistance of him and my uncle John, and some other relations, I got forty pounds, and a promise of thirty pounds a year to maintain me at Leyden: there I studied physic two years and seven months, knowing it would be useful in long voyages. Soon after my return, I accepted an advantageous offer on board the Antelope.`,

    // 20
    `When I was a boy, there was but one permanent ambition among my comrades in our village on the west bank of the Mississippi River. That was, to be a steamboatman. We had transient ambitions of other sorts, but they were only transient. When a circus came and went, it left us all burning to become clowns; the minstrel show left us with a desire to join that company; even the pirate business had its brief day of popularity; but these ambitions faded out, each in its turn; the ambition to be a steamboatman always remained. Once a day a cheap, gaudy packet arrived upward from St. Louis, and another downward from Keokuk. Before these events, the day was glorious with expectancy; after them, the day was a dead and empty thing. Not only the boys, but the whole village, felt this. After all these years I can picture that old time just as it was then: the white town drowsing in the sunshine of a summer morning; the streets empty, or pretty nearly so; one or two dogs sleeping comfortable in the dust.`

  ],
  bangla: [
    // 1
    `১৯৪৮ সালের কথা। তখন ঢাকায় এসেছি, ঢাকা বিশ্ববিদ্যালয়ে ভর্তি হয়েছি। ছাত্ররাজনীতি আবার নতুন করে শুরু করতে হবে। আমরা কয়েকজন কর্মী পূর্ব পাকিস্তান মুসলিম ছাত্রলীগ গঠন করার সিদ্ধান্ত নিলাম। ৪ জানুয়ারি ফজলুল হক হলের অ্যাসেম্বলি হলে এক সভা ডাকা হলো। সেখানে সর্বসম্মতিক্রমে পূর্ব পাকিস্তান মুসলিম ছাত্রলীগ গঠিত হলো। এর পর থেকেই বাংলা ভাষার বিরুদ্ধে ষড়যন্ত্র শুরু হতে থাকে। খাজা নাজিমুদ্দীন সাহেব গণপরিষদে দাঁড়িয়ে উর্দুকেই পাকিস্তানের একমাত্র রাষ্ট্রভাষা করার কথা বললেন। আমরা সাথে সাথে প্রতিবাদ করলাম। ছাত্ররা ধর্মঘট করল এবং রাজপথে নেমে এলো। আমরা বিভিন্ন জেলায় ঘুরে ঘুরে সভা করতে লাগলাম এবং রাষ্ট্রভাষা বাংলার পক্ষে জনমত গড়ে তুললাম। মাতৃভাষার প্রতি এ দেশের মানুষের যে গভীর ভালোবাসা দেখেছি, তা কোনোদিন ভোলার নয়। আমরা ১৯৪৮ সালের ১১ মার্চ ধর্মঘটের ডাক দিলাম। সেদিন সকালে সচিবালয়ের সামনে ও অন্যান্য সরকারি অফিসের সামনে পিকেটিং শুরু হলো। পুলিশ লাঠিচার্জ করল এবং বহু ছাত্র আহত হলো। আমিও গ্রেফতার হলাম। সেই দিনটি ছিল আমাদের ভাষা আন্দোলনের এক ঐতিহাসিক মাইলফলক। যে জাতি নিজের মায়ের ভাষার জন্য লড়াই করতে জানে, সে জাতিকে কোনো শাসকগোষ্ঠী দাবিয়ে রাখতে পারে না। এই আন্দোলনের পথ ধরেই আমাদের পরবর্তী স্বাধিকার চেতনার বিকাশ ঘটেছিল।`,

    // 2
    `কারাগারের ছোট কুঠুরিতে বসে বসে কত কথাই মনে পড়ে। বাইরে যখন ছিলাম, তখন মানুষের কোলাহলে ব্যস্ত থাকতাম। আর এখানে চার দেয়ালের মাঝে শুধু নিঃসঙ্গতা। সকালবেলা যখন সূর্যের আলো এসে ঘরের মেঝেতে পড়ে, তখন মনে হয় যেন বাইরের আলো আমাকে ডাকছে। জেলখানার বাগানটিতে কয়েকটা গোলাপ আর গন্ধরাজ ফুলের গাছ আছে। প্রতিদিন সকালে উঠে আমি সেই গাছগুলোর গোড়ায় পানি দিই। ফুলগুলো যখন ফোটে, তখন মনে এক অদ্ভুত প্রশান্তি আসে। গাছপালা আর ফুল যেন নির্বাক ভাষায় কথা বলে। মানুষ মানুষকে কত কষ্ট দিতে পারে, কত নির্যাতন করতে পারে, তা এই কারাগারের ভেতরে না এলে বোঝা যায় না। দুপুরবেলা যখন তীব্র রোদ ওঠে, তখন সেলের ভেতরে বাতাস ভারী হয়ে ওঠে। সন্ধ্যার দিকে কয়েদিদের লক-আপ করা হয়। এক একজনের মনের কথা শুনলে চোখে পানি আসে। কত নিরপরাধ মানুষ বছরের পর বছর বিনা বিচারে পচে মরছে। তবুও আমি আশাবাদী মানুষ, হতাশা আমার স্বভাবে নেই। অন্যায়ের বিরুদ্ধে সত্যের জয় হবেই। বাংলার মেহনতী মানুষ, যারা দিনরাত মাথার ঘাম পায়ে ফেলে কাজ করে, তাদের মুক্তির জন্যই তো আমার এই সংগ্রাম। জীবনের অধিকাংশ সময় জেলেই কেটে গেল, তাতে আমার কোনো আক্ষেপ নেই। দেশের মানুষের মুখে যদি এক চিলতে হাসি ফোটাতে পারি, তবেই আমার জীবনের সার্থকতা।`,

    // 3
    `ভায়েরা আমার, আজ দুঃখ ভারাক্রান্ত মন নিয়ে আপনাদের সামনে হাজির হয়েছি। আপনারা সবই জানেন এবং বোঝেন। আমরা আমাদের জীবন দিয়ে চেষ্টা করেছি। কিন্তু দুঃখের বিষয়, আজ ঢাকা, চট্টগ্রাম, খুলনা, রাজশাহী, রংপুরে আমার ভাইয়ের রক্তে রাজপথ রঞ্জিত হয়েছে। আজ বাংলার মানুষ মুক্তি চায়, বাংলার মানুষ বাঁচতে চায়, বাংলার মানুষ তার অধিকার চায়। কি অন্যায় করেছিলাম? নির্বাচনের পরে বাংলাদেশের মানুষ সম্পূর্ণভাবে আমাকে, আওয়ামী লীগকে ভোট দেন। আমাদের ন্যাশনাল অ্যাসেম্বলি বসবে, আমরা সেখানে শাসনতন্ত্র তৈরি করব এবং এই দেশকে আমরা গড়ে তুলব, এ দেশের মানুষ অর্থনৈতিক, রাজনৈতিক ও সাংস্কৃতিক মুক্তি পাবে। কিন্তু দুঃখের বিষয়, আজ দুঃখের সঙ্গে বলতে হয়, তেইশ বৎসরের করুণ ইতিহাস বাংলার অত্যাচারের, বাংলার মানুষের রক্তের ইতিহাস। রক্ত যখন দিয়েছি, রক্ত আরো দেব, এ দেশের মানুষকে মুক্ত করে ছাড়ব ইনশাল্লাহ্। প্রত্যেক ঘরে ঘরে দুর্গ গড়ে তোলো। তোমাদের যা কিছু আছে তাই নিয়ে শত্রুর মোকাবিলা করতে হবে, এবং জীবনের তরে রাস্তাঘাট যা যা আছে আমি যদি হুকুম দেবার নাও পারি, তোমরা বন্ধ করে দেবে। আমরা ভাতে মারব, আমরা পানিতে মারব। সাত কোটি মানুষকে দাবায়ে রাখতে পারবা না। এবারের সংগ্রাম আমাদের মুক্তির সংগ্রাম, এবারের সংগ্রাম স্বাধীনতার সংগ্রাম! জয় বাংলা!`,

    // 4
    `আজ আমার বয়স সাতাশ মাত্র। এ জীবনটা না দৈর্ঘ্যের হিসাবে বড়, না গুণের হিসাবে। তবু ইহার একটি বিশেষ মূল্য আছে। ইহা সেই ফুলের মতো যাহার বুকের উপরে ভ্রমর আসিয়া বসিয়াছিল, এবং সেই পদক্ষেপে তাহার ইতিহাসটি ফলের মতো সফল হইয়া উঠিয়াছে। ছোটো কথাটি বলিয়া লই। ভালোমানুষের মতো যে ছেলেটিকে সচরাচর দেখা যায়, আমি সেই দলের। অভিভাবকেরা আমার স্বভাব দেখিয়া মুগ্ধ হইতেন। ছেলেবেলা হইতেই পড়াশোনায় কোনো ত্রুটি করি নাই। পাস তো ভালোই করিয়াছি, কিন্তু সংসারের কোনো কাজের উপযুক্ত হই নাই। আমার আসল অভিভাবক ছিলেন মামা। তিনি আমার চেয়ে বড়জোর বছর ছয়েকের বড়, কিন্তু ফল পাকিলে যেমন হয় তেমনি রসালো ও শক্ত। সংসারের সমস্ত দায়িত্ব তাঁহারই কাঁধে ছিল। আমি কোনো বিষয়েই মাথা ঘামাইতাম না। বিবাহের সম্বন্ধ আসিতে লাগিল। মামার এক অদ্ভুত স্বভাব ছিল, কোনো কিছুতেই তিনি সহজে সম্মত হইতেন না। হরিহরবাবু আসিয়া কন্যার রূপগুণের প্রশংসা করিলে মামা ভ্রূকুটি করিলেন। কিন্তু কন্যার পিতার কোনো বড় দাবি নাই এবং তিনি কন্যার বিবাহের জন্য উপযুক্ত পাত্র খুঁজিতেছেন জানিয়া মামা কিছুটা নরম হইলেন। হরিশ আসিয়া বলিল, পাত্রী যে স্বয়ং লক্ষ্মী, একবার চক্ষে না দেখিলে বিশ্বাস হইবে না। আমার মনের মধ্যেও এক অচেনা রূপসীর ছবি ভাসিয়া উঠিত, যাহার মুখে কোনো কৃত্রিমতা নাই, যে আপন সৌন্দর্যে আপনি উজ্জ্বল।`,

    // 5
    `বলাইয়ের প্রকৃতিটা কেমন যেন অদ্ভুত রকমের। ঘাস কাটার শব্দ শুনিলে তাহার বুকে যেন ব্যথা লাগিত। বাগানের কোনো গাছ হইতে পাতা ছিঁড়িলে সে মনে মনে অস্থির হইয়া উঠিত। বাড়ির পথের ধারে একটি শিমুল গাছের চারা গজাইয়াছিল। প্রতিদিন সকালে বলাই গিয়া সেই চারাটির দিকে চাহিয়া থাকিত। গাছটি যখন একটু একটু করিয়া বড় হইতে লাগিল, বলাইয়ের আনন্দের আর সীমা রহিল না। সে তাহার কাকাকে আসিয়া বলিল, কাকা, ওই গাছটিকে কাটিয়ো না। কাকা হাসিয়া বলিলেন, ও তো জংলি গাছ, পথের মধ্যে বড় হইলে যাতায়াতের অসুবিধা হইবে। বলাই কান্নাকাটি করিয়া গাছটিকে বাঁচাইল। বর্ষার দিনে যখন বৃষ্টি পড়িত, তখন বলাই জানালার ধারে বসিয়া সেই গাছটির ভিজিয়া যাওয়া দেখিত। তাহার মনে হইত, গাছটির যেন প্রাণ আছে, সে যেন আকাশের দিকে হাত বাড়াইয়া বৃষ্টির ফোঁটা গ্রহণ করিতেছে। বলাইয়ের মা মারা গিয়াছিলেন যখন তাহার বয়স অল্প। তাই প্রকৃতিই ছিল তাহার একমাত্র সঙ্গী ও খেলার সাথি। বাগানের ফুলগুলি যখন বাতাসে দুলিত, বলাই ভাবিত তাহারা যেন তাহাকে ডাকিয়া খেলায় যোগ দিতে বলিতেছে। তাহার চাচি তাহাকে বড় ভালোবাসিতেন, কিন্তু বলাইয়ের এই অদ্ভুত স্বভাব দেখিয়া তিনিও কখনো কখনো অবাক হইয়া যাইতেন। গাছপালা ও প্রকৃতির প্রতি এমন গভীর মমতা সচরাচর মানুষের মধ্যে দেখা যায় না।`,

    // 6
    `ফটিক চক্রবর্তীর মতো দুরন্ত ছেলে গ্রামে আর একটিও ছিল না। তাহার দলবল লইয়া সে নদীর ধারে চরে বেড়াইতে ভালোবাসিত। একবার গ্রামের ঘাটে একটি বড় শালকাঠের গুঁড়ি পড়িয়া ছিল। ফটিক ফন্দি আঁটিল, গুঁড়িটাকে সবাই মিলিয়া ঠেলিয়া জলে ভাসাইয়া দিবে। গুঁড়ির মালিক যখন আসিয়া দেখিবে কাঠ নাই, তখন তাহার মুখখানা কেমন হইবে ভাবিয়া তাহারা হাসিয়া খুন হইল। কিন্তু ঠিক সেই সময় ফটিকের ছোট ভাই মাখনলাল আসিয়া সেই গুঁড়ির উপরে গম্ভীর হইয়া বসিয়া রহিল। ফটিক তাহাকে সরিয়া যাইতে বলিল, কিন্তু মাখন নড়িল না। তখন ফটিক হুকুম দিল, মাখনসুদ্ধ গুঁড়িটাকে ঠেলিয়া ফেলিয়া দাও। গুঁড়ি গড়াইতে লাগিল এবং মাখন মাটিতে পড়িয়া কাদায় মাখামাখি হইল। মাখন উঠিয়া ফটিককে মারিতে লাগিল এবং কাঁদিতে কাঁদিতে বাড়ি চলিয়া গেল। ফটিক জানিত বাড়িতে গেলে মায়ের হাতে মার খাইতে হইবে। এমন সময় তাহাদের মামা বিশ্বম্ভরবাবু বহুকাল পরে সহর হইতে দেশে আসিয়া পৌঁছিলেন। তিনি ফটিককে দেখিয়া বলিলেন, তোর পড়াশোনার বড় ক্ষতি হইতেছে, তুই আমার সঙ্গে কলিকাতায় চল, সেখানে স্কুলে ভর্তি করিয়া দিব। ফটিক তো আনন্দে নাচিতে লাগিল। মাকে ছাড়িয়া যাইতে তাহার একটুও দুঃখ হইল না। কিন্তু কলিকাতায় গিয়া মামার বাড়িতে সে যে কী নিদারুণ যন্ত্রণার মধ্যে পড়িল, তাহা কে জানিত।`,

    // 7
    `যৌবনকে যাহারা শুধু বয়সের ফ্রেমে বাঁধিয়া রাখিতে চায়, তাহারা ভুল করে। যৌবন বয়সের মাপকাঠিতে মাপা যায় না, যৌবন মনের একটি চিরন্তন অবস্থা। যাহার প্রাণ অনন্ত আকুলতায় চঞ্চল, যাহার চক্ষে নব নব স্বপ্নের রঙিন মায়া, যাহার বক্ষে বাধার পাহাড় ভাঙিয়া ফেলিবার দুর্জয় সাহস, সে-ই তো তরুণ, সে-ই তো চিরযৌবনের অধিকারী। বৃদ্ধ সে, যে চলিতে ভয় পায়, যে অতীতকে আঁকড়িয়া ধরিয়া পড়িয়া থাকিতে চায়। যৌবনের ধর্মই হইল সৃষ্টির উল্লাসে মাতিয়া ওঠা, জীর্ণ পুরাতন সংস্কারকে গুঁড়াইয়া দিয়া নতুনের কেতন উড়ানো। যৌবন কোনোদিন আপস করিতে জানে না। সে মৃত্যুভয়কে জয় করিয়া নবজীবনের আহ্বানে ছুটিয়া যায়। আজ এই পরাধীন, জড়ত্বগ্রস্ত সমাজের বুকে সেই দুর্জয় তারুণ্যের বড়ই প্রয়োজন। তরুণের শক্তি অনন্ত, তাহার সম্ভাবনা অসীম। সে যখন জাগে, তখন ধরণী কাঁপিয়া ওঠে, আকাশের মেঘ ছিন্নভিন্ন হইয়া যায়। আজ আমাদের দেশের দিকে চাহিয়া দেখো, সর্বত্র হতাশা ও ক্লান্তি। এই ক্লান্তির অবসান ঘটাইতে পারে কেবল যৌবনের উদ্দাম প্রাণের প্রবাহ। যে জাতি তরুণদের অবহেলা করে, সে জাতি বাঁচিতে পারে না। যে যৌবন অন্যায় দেখিলে রুখিয়া দাঁড়ায়, যে যৌবন নিপীড়িতের ক্রন্দন শুনিলে খড়গহস্ত হইয়া বাহির হয়, সেই যৌবনের জয়গানই আমি গাহিতেছি। এসো তরুণ, এসো নবীন, জাগাও এই ঘুমন্ত জাতিকে!`,

    // 8
    `আমার উপর অভিযোগ, আমি রাজবিদ্রোহী। তাই আজ আমি রাজকারাগারে বন্দী এবং রাজদ্বারে অভিযুক্ত। একধারে রাজার রাজদণ্ড, অন্যধারে পরমেশ্বরের ন্যায়দণ্ড। একদিকে রাজার প্রতিনিধি বিচারক, অপরদিকে ভগবানের প্রতিনিধি স্বয়ং কবি। আমি সত্য প্রকাশ করিয়াছি বলিয়া আজ আমি অপরাধী। কিন্তু সত্য তো কোনো রাজার বা কোনো সাম্রাজ্যের দাস নহে। সত্য স্বয়ং সৃষ্টিকর্তার বাণী। রাজা আজ বাহুবলের অহংকারে অন্ধ হইয়া সেই সত্যের কণ্ঠরোধ করিতে উদ্যত হইয়াছেন। কিন্তু ইতিহাস সাক্ষ্য দেয়, কোনো অত্যাচারী শাসকের খড়্গ চিরদিন সত্যের দীপশিখাকে নিভাইতে পারে নাই। আমাকে হয়তো ফাঁসিকাষ্ঠে ঝুলাইতে পারো, কারাগারে আবদ্ধ করিয়া রাখিতে পারো, কিন্তু আমার অন্তরের যে সত্যবাণী আকাশে-বাতাসে ছড়াইয়া পড়িয়াছে, তাহাকে তোমরা ধ্বংস করিবে কেমন করিয়া? আমি জানি, সত্যের পথ বড়ই কঠিন, কিন্তু সেই পথই একমাত্র মুক্তির পথ। কারাগারের অন্ধকার আমাকে স্তব্ধ করিতে পারিবে না। আমার কণ্ঠরোধ করিলেও আমার লেখনীর রক্তবিন্দু নবীন প্রাণের মাঝে বিদ্রোহের আগুন জ্বালাইয়া রাখিবে। ভগবানের আশীর্বাদ আমার মস্তকে আছে, তাই কোনো নরপতির ভীতি আমাকে বিচলিত করিতে পারিবে না। সত্যের জয় হইবেই, মিথ্যার প্রাসাদ চূর্ণবিচূর্ণ হইবে। আমি নির্ভীক চিত্তে সেই অনন্ত পরমেশ্বরের ন্যায়বিচারের জন্য অপেক্ষা করিতেছি।`,

    // 9
    `মৃত্যুঞ্জয়ের জাত লইয়া গ্রামের সমাজে মহা হুলুস্থুল পড়িয়া গেল। সে ছিল মালোপাড়ার এক সাপুড়ের মেয়ে বিলাসীর হাতের সেবা লইয়া বাঁচিয়া উঠা এক নিঃসম্পর্কিত যুবক। কঠিন রোগে যখন মৃত্যুঞ্জয় শয্যাশায়ী হইয়াছিল, তাহার জ্ঞাতি-ভাইয়েরা কেহ তাহার খোঁজ লইতে আসে নাই। দিনরাত জাগিয়া নিজের প্রাণ বাজি রাখিয়া যে মেয়েটি তাহাকে মৃত্যুর মুখ হইতে ফিরাইয়া আনিল, সে হইল অস্পৃশ্য বিলাসী। গ্রামের সমাজপতিরা বিচার বসাইলেন। তাহারা বলিলেন, এ কেমন কথা! এক কায়েতের ছেলে সাপুড়ের মেয়ের হাতে অন্ন খাইবে? জাত নষ্ট করিবে? তাহারা মৃত্যুঞ্জয়কে ভিটা হইতে উচ্ছেদ করিবার ষড়যন্ত্র করিল। কিন্তু মৃত্যুঞ্জয় ও বিলাসী কোনো ভণ্ড সমাজকে ভয় পাইল না। বিলাসীর মতো এমন নিষ্কলঙ্ক সেবা ও আত্মত্যাগ আমি জীবনে আর কোথাও দেখি নাই। মৃত্যুঞ্জয় যখন সুস্থ হইল, তখন সে বিলাসীকে ত্যাগ করিতে অস্বীকার করিল। সে বলিল, যে আমাকে জীবনের আলো ফিরাইয়া দিয়াছে, তাহাকে ছাড়িয়া স্বর্গে যাইবার লোভও আমার নাই। গ্রামের লোকে একঘরে করিল, কিন্তু তাহাদের দাম্পত্য জীবনের সুখের আলো নিভিল না। তাহারা সাপের বিষ নামাইবার মন্ত্র শিখিয়া বনের ধারে আপন কুটিরে পরম শান্তিতে দিন কাটাইতে লাগিল। মানুষের আসল পরিচয় তাহার ভালোবাসায়, তাহার ত্যাগ ও সেবার মহিমায়, কোনো সামাজিক জাতপাতের কৃত্রিম বিধিনিষেধে নহে।`,

    // 10
    `বই পড়ার অভ্যাসটা যে একটি শ্রেষ্ঠ গুণ, সে বিষয়ে বোধহয় কোনো বিতর্ক নাই। কিন্তু আমাদের এই দেশে বই পড়ার প্রতি মানুষের তেমন উৎসাহ দেখা যায় না। আমরা পাস করিবার জন্য পড়ি, বিদ্যা অর্জনের জন্য পড়ি না। আমাদের শিক্ষাব্যবস্থায় এমন এক গলদ রহিয়া গিয়াছে যে, স্কুল-কলেজের পাঠ্যবই গিলিয়া পরীক্ষা পাস করাই যেন জীবনের একমাত্র লক্ষ্য হইয়া দাঁড়াইয়াছে। ফলে পরীক্ষা শেষ হইলেই আমরা বই ছুঁড়িয়া ফেলিয়া দিই। সাহিত্যের যে একটি আনন্দ আছে, মনের ক্ষুধা মেটাইবার যে একটি শক্তি আছে, তাহা আমরা উপলব্ধি করিতে পারি না। অর্থকরী বিদ্যা না হইলে মানুষ তাহার কোনো মূল্য দিতে চায় না। কিন্তু মানবাত্মার মুক্তির জন্য, জ্ঞানের দিগন্ত প্রসারিত করিবার জন্য সাহিত্যচর্চার কোনো বিকল্প নাই। লাইব্রেরি হইল সেই স্থান, যেখানে মানুষের মন স্বাধীনভাবে বিচরণ করিতে পারে। স্কুল-কলেজ আমাদিগকে যে শিক্ষা দেয়, তাহা খাঁচার পাখির মতো; কিন্তু লাইব্রেরির বিদ্যা আমাদিগকে মুক্ত আকাশের পাখির মতো ডানা মেলিতে শেখায়। যে জাতি মনে বড় নয়, সে জাতি জ্ঞানে বড় হইতে পারে না। জ্ঞানের আনন্দই মানুষকে সত্যিকার অর্থে মানুষ করিয়া তোলে। তাই আমাদের কর্তব্য পাঠাগারের প্রতিষ্ঠা করা এবং মানুষকে বই পড়িতে উৎসাহিত করা। বই পড়াই একমাত্র উপায় যাহার মাধ্যমে আমরা আমাদের সংকীর্ণতার গণ্ডি কাটাইয়া বিশ্বমানবের মিলনমেলায় প্রবেশ করিতে পারি।`,

    // 11
    `আমরা সমাজের অর্ধ অঙ্গ। সমাজ যদি একটি রথ হয়, তবে নারী ও পুরুষ তাহার দুইটি চাকা। একটি চাকা ছোট এবং অপরটি বড় হইলে সে রথ কি কখনো সোজা পথে চলিতে পারে? কিন্তু আমাদের দেশের পুরুষেরা নারীকে চিরকাল অজ্ঞতার অন্ধকারে আবদ্ধ করিয়া রাখিয়াছেন। ধর্মের দোহাই দিয়া, প্রথার দোহাই দিয়া নারীকে গৃহকোণের বন্দিনী করিয়া রাখা হইয়াছে। নারী যে একজন স্বতন্ত্র মানুষ, তাহারও যে বুদ্ধি, মেধা ও প্রতিভা আছে, তাহা কেহ স্বীকার করিতে চাহে না। শিক্ষার আলো হইতে বঞ্চিত রাখিয়া আমাদিগকে কেবল পরনির্ভরশীল করিয়া তোলা হইয়াছে। এই দাসত্ব হইতে মুক্তি পাইতে হইলে নারীকে বিদ্যাশিক্ষা অর্জন করিতে হইবে। নিজের পায়ে দাঁড়াইতে হইবে। পুরুষেরা আমাদিগকে পদতলে রাখিয়া গৌরব অনুভব করেন, কিন্তু তাহারা ভাবেন না যে, জননী যদি দুর্বল ও মূর্খ থাকেন, তবে সন্তান কখনো বীর বা জ্ঞানী হইতে পারে না। তাই বলি, জাগিতে হইবে আমাদিগকেই। পরের দয়ার উপর নির্ভর করিয়া কোনোদিন সম্মান লাভ করা যায় না। নিজের অধিকার নিজেদেরই আদায় করিয়া লইতে হইবে। কন্যা সন্তানকে সুশিক্ষিত করিয়া তুলিলে তবেই একটি পরিবার, একটি সমাজ এবং একটি দেশ উন্নত হইতে পারে। জাগো নারী, জড়তা পরিহার করো, জ্ঞানের আলোকবর্তিকা হস্তে লইয়া সম্মুখপানে অগ্রসর হও!`,

    // 12
    `কাবুলে আসিয়া বাসা লইবার পরদিনই আব্দুর রহমানের সহিত পরিচয় হইল। সে আমার চাকর নহে, যেন সাক্ষাৎ এক দৈত্যাকার রক্ষক। তাহার দেহের দৈর্ঘ্য ছয় ফুট চার ইঞ্চি, কাঁধ দুইখানা যেমন চওড়া, তেমনি বলিষ্ঠ। সে আসিয়া গম্ভীর কণ্ঠে কুর্নিশ করিয়া দাঁড়াইল। আমি তাহাকে বলিলাম, দেখো আব্দুর রহমান, তোমার রান্নাবান্না কেমন আমি জানি না, তবে আমি সাধারণ ডাল-ভাত খাইতেই অভ্যস্ত। সে মাথা নাড়িয়া প্রস্থান করিল। কিন্তু আহারের সময় যখন টেবিল সাজাইল, তখন আমার চক্ষু চড়কগাছ। কাবাব, পোলাও, কোরমা, ফলমূল—এত খাবার যে এক ডজন মানুষ পেট ভরিয়া খাইতে পারে। আমি বলিলাম, এত খাবার আমি একলা খাইব কেমন করিয়া? আব্দুর রহমান স্মিত হাসিয়া বলিল, সাহেব, আপনি অতিথি, কাবুলের আতিথেয়তার কোনো সীমা নাই। আপনি যাহা পারেন খান, বাকিটা আমি দেখিব। পরে দেখিলাম, আমার খাওয়া শেষ হইলে সে একাই সেই বিশাল ভোজপর্বের বাকি অংশ পরম তৃপ্তির সহিত সাবাড় করিয়া দিল। পরদিন সকালে উঠিয়া দেখিলাম, আব্দুর রহমান এক বালতি গরম জল আর তাজা ফলের রস লইয়া হাজির। তাহার মুখে সেই চিরন্তন প্রশান্ত হাসি। আমি বলিলাম, আব্দুর রহমান, এত যত্নের কোনো প্রয়োজন ছিল না। সে বলিল, মেহমান খোদার দান, মেহমানের সেবা করাই আমাদের আফগানদের সবচেয়ে বড় গৌরব। তাহার এই সরল ভক্তি দেখিয়া আমার অন্তর শ্রদ্ধায় ভরিয়া গেল। এমন সরল ও খাদ্যরসিক ভৃত্য জীবনে কমই দেখিয়াছি।`,

    // 13
    `যুদ্ধ যখন শুরু হলো, তখন আমরা কেউ বন্দুক চালাতে জানতাম না। কিন্তু চোখের সামনে যখন দেখলাম আমাদের গ্রাম পুড়ছে, মা-বোনের ওপর নির্যাতন চলছে, তখন বুকের ভেতর আগুন জ্বলে উঠল। আমরা সীমান্ত পার হয়ে ট্রেনিং ক্যাম্পে গেলাম। বৃষ্টিতে ভিজে, কাদামাটিতে শুয়ে রাইফেল চালানো শিখলাম। আমাদের কোনো আধুনিক অস্ত্র ছিল না, কিন্তু আমাদের মনে ছিল স্বাধীনতার অদম্য আকাঙ্ক্ষা। রাতের অন্ধকারে আমরা গেরিলা আক্রমণ চালাতাম। শত্রু যখন বাংকারে বসে থাকত, আমরা নিঃশব্দে নদী সাঁতরে গিয়ে তাদের ওপর ঝাঁপিয়ে পড়তাম। মৃত্যু আমাদের চোখের সামনে নাচত, কিন্তু কারো মনে কোনো ভয় ছিল না। আমরা জানতাম, আমরা যদি প্রাণ দিই, তবেই এ দেশের কোটি কোটি মানুষ স্বাধীন বাতাসে নিঃশ্বাস নিতে পারবে। গ্রামের পর গ্রাম পুড়িয়ে দিয়েও হানাদাররা আমাদের মনোবল ভাঙতে পারেনি। আমরা জানতাম, রক্ত ঝরবে, বহু সাথী হারাবে, কিন্তু দিনশেষে লাল-সবুজের পতাকা এই বাংলার আকাশে উড়বেই। প্রতিটি গেরিলার চোখে ছিল প্রতিশোধের আগুন আর অন্তরে ছিল স্বদেশের প্রতি গভীর ভালোবাসা। সেই ভালোবাসার শক্তিতেই আমরা পরাক্রমশালী শত্রুকে পরাজিত করেছিলাম। একাত্তরের সেই উত্তাল দিনগুলোতে প্রতিটি তরুণ যেন এক একটি জ্বলন্ত মশালে পরিণত হয়েছিল। দেশের স্বাধীনতার চেয়ে বড় কোনো ধর্ম তখন আমাদের কাছে ছিল না।`,

    // 14
    `বৃষ্টির দিনে নুরুল হুদার বাসা থেকে বের হওয়া এক মহা ঝামেলার ব্যাপার। কিন্তু আজ তাকে কলেজে যেতেই হবে। প্রিন্সিপাল তলব করেছেন। মিলিটারিরা কলেজের দেয়ালের পাশে ক্যাম্প করেছে। নুরুল হুদা তার শ্যালক মিন্টুর রেখে যাওয়া রেইনকোটটি গায়ে চড়াল। মিন্টু গত মাসে মুক্তিযুদ্ধে যোগ দিতে চলে গেছে। সেই থেকে মিন্টুর রেইনকোটটি আলমারিতে ঝুলছিল। নুরুল হুদা যখন সেই কোটটি পরল, তখন তার শরীরের ভেতরে এক অদ্ভুত শিহরণ খেলে গেল। মনে হলো মিন্টুর সাহস, মিন্টুর দেশপ্রেম যেন এই রেইনকোটের সুতোয় সুতোয় মিশে আছে। যে নুরুল হুদা সামান্য শব্দ শুনলেই ভয়ে কাঁপত, আজ সে রাস্তায় নেমে মিলিটারি ট্রাক দেখেও একটুও ঘাবড়াল না। কলেজের পিয়ন এসে যখন তাকে মিলিটারিদের সামনে নিয়ে গেল, তখন সে সোজা হয়ে দাঁড়াল। মিলিটারিরা যখন তাকে জেরা করতে লাগল, নুরুল হুদা একটি কথাও প্রকাশ করল না। মিলিটারি অফিসারের কর্কশ কণ্ঠের প্রশ্নের মুখেও নুরুল হুদার চোয়াল শক্ত হয়ে রইল। সে অনুভব করল, মিন্টু যেন তার পাশেই দাঁড়িয়ে আছে। তার বুকের ভেতরে যে ভয় এতদিন বাসা বেঁধেছিল, তা এক নিমেষে ধূলিসাৎ হয়ে গেল। এই রেইনকোট কেবল একটি পোশাক নয়, এ যেন একাত্তরের মুক্তিকামী মানুষের অটুট শপথ। রেইনকোটটি যেন তাকে সব ধরনের ভীতি ও দুর্বলতা থেকে মুক্ত করে এক অপরাজেয় যোদ্ধায় পরিণত করেছে।`,

    // 15
    `দরিয়া বিবির সংসারের অভাব কোনোদিন দূর হইল না। সকাল হইতে সন্ধ্যা পর্যন্ত সে মাটির হাঁড়ির মতো পুড়িয়া খাঁটি হইয়াছে, কিন্তু তাহার সন্তানের মুখে দুবেলা দুমুঠো অন্ন তুলিয়া দিতে পারে নাই। তাহার স্বামী ছিল ভবঘুরে টাইপের মানুষ, সংসারের প্রতি তাহার কোনো টান ছিল না। কিন্তু দরিয়া বিবি হাল ছাড়িল না। সে অন্যের বাড়ি ধান ভানিয়া, শাকপাতা কুড়াইয়া নিজের সন্তানদের আগলাইয়া রাখিল। শীতের রাতে যখন কনকনে ঠাণ্ডা বাতাস বহিত, সে ছেঁড়া কাঁথা দিয়া সন্তানদের গা ঢাকিয়া নিজে শীতে কাঁপিত। মাতৃত্বের এই এক আশ্চর্য শক্তি। জগতে সন্তানের মুখের চেয়ে মধুর আর কোনো দৃশ্য মায়ের কাছে নাই। সমস্ত দুঃখ, সমস্ত লাঞ্ছনা সে নীরবে সহ্য করিয়াছে কেবল এই আশায় যে, তাহার সন্তানেরা একদিন বড় হইবে, মানুষের মতো মানুষ হইবে। সন্ধ্যায় যখন আঁধার নামিত, দরিয়া বিবি ভাঙ্গা ঘরের মেঝেতে বসিয়া সন্তানদের মুখের দিকে চাহিয়া দীর্ঘশ্বাস ফেলিত। তাহার নিজের পেটে ক্ষুধা ছিল, কিন্তু সে ক্ষুধা সে ভুলিয়া যাইত সন্তানের মুখে একটুখানি ফ্যান তুলিয়া দিয়া। জননীর এই অসীম ধৈর্য ও আত্মবলিদানই তো শতাব্দীর পর শতাব্দী ধরিয়া বাংলার গৃহকোণকে ধারণ করিয়া রাখিয়াছে। বাংলার পল্লীগ্রামের ঘরে ঘরে এমন লক্ষ লক্ষ জননী নীরবে নিজেদের জীবন বিসর্জন দিয়া আমাদের সমাজকে বাঁচাইয়া রাখিয়াছেন।`,

    // 16
    `যাঁহারা ইংরাজি পড়িয়াছেন, তাঁহাদের অনেকে মনে করেন যে, বাঙ্গালা ভাষায় গভীর চিন্তা প্রকাশ করিবার মতো শক্তি নাই। ইহা নিতান্ত ভ্রান্ত ধারণা। যে ভাষায় রামায়ণ, মহাভারত অনুবাদ হইয়াছে, যে ভাষায় বৈষ্ণব পদাবলী রচিত হইয়াছে, সে ভাষার দৈন্য কোথায়? মাতৃভাষার প্রতি যাহাদের শ্রদ্ধা নাই, তাহারা কোনোদিন প্রকৃত জ্ঞান লাভ করিতে পারে না। ইংরাজি আমরা শিখিব জ্ঞানের প্রয়োজনে, কিন্তু ভাব প্রকাশের জন্য আমাদের নিজস্ব ভাষাই একমাত্র আশ্রয়। পরভাষায় কোনো জাতি মহৎ হইতে পারে না। আপনি যদি দেশের মানুষের হৃদয়ে প্রবেশ করিতে চান, তবে তাহাদের মাতৃভাষাতেই কথা বলিতে হইবে। বাঙ্গালা ভাষা সংস্কৃতের কন্যা হইলেও নিজস্ব প্রাণশক্তিতে বলীয়ান। ইহাকে অবহেলা করিয়া যাহারা কেবল বিদেশি ভাষার অনুকরণ করিতে চান, তাঁহারা নিজের শিকড়কেই অস্বীকার করেন। যে ভাষা দিয়ে আমরা আমাদের অন্তরের আনন্দ ও বেদনা প্রকাশ করি, সেই ভাষাকে উন্নত করাই আমাদের প্রধান দায়িত্ব। বঙ্গদেশের সাহিত্যিকগণের উচিত দেশীয় ভাষার প্রতি পূর্ণ মনোযোগ দেওয়া। সংস্কৃত হইতে শব্দ গ্রহণ করো, কিন্তু ভাষার সরলতা ও মাধুর্য যেন নষ্ট না হয়। মাতৃভাষার মাধ্যমেই সমগ্র জাতির মননশীলতার বিকাশ সম্ভব। মাতৃভাষার উন্নতিতেই একটি জাতির সামগ্রিক উন্নতি নির্ভর করে।`,

    // 17
    `মহর্ষি কণ্বের তপোবন এক পরম শান্তিময় স্থান। সেখানে হিংস্র জীবজন্তুরাও মানুষের সহিত পরম সখ্যতায় বাস করিত। সেই তপোবনের এক প্রান্তে শকুন্তলা তাহার দুই সখী অনুসূয়া ও প্রিয়ংবদা সহ তরুলতাগণকে জলসেচন করিতেছিলেন। আশ্রমের মৃগশিশুরা শকুন্তলার অঞ্চলের প্রান্ত ধরিয়া যেন স্নেহের পরশ ভিক্ষা করিতেছিল। রাজা দুষ্মন্ত মৃগয়া করিতে আসিয়া সেই তপোবনের প্রবেশদ্বারে রথ রাখিয়া পদব্রজে প্রবেশ করিলেন। তিনি শকুন্তলার অনিন্দ্যসুন্দর রূপ দেখিয়া বিস্মিত ও মুগ্ধ হইলেন। তাঁহার মনে হইল, রাজপ্রাসাদের সমস্ত ঐশ্বর্য ও মণিমুক্তার চেয়ে এই তপোবনের প্রাকৃতিক সারল্য শতগুণে শ্রেষ্ঠ। শকুন্তলার নয়নে কোনো ছলনা ছিল না, তাহার বাক্যে কোনো চাতুর্য ছিল না। সে ছিল প্রকৃতির এক নির্মল উপহার। রাজা দুষ্মন্ত শকুন্তলার সহিত আলাপ করিয়া বুঝিতে পারিলেন যে, রূপের চেয়েও শকুন্তলার স্বভাব অধিকতর মধুর ও পবিত্র। কণ্বমুনির অনুপস্থিতিতে তপোবনের অতিথি সৎকারের দায়িত্ব শকুন্তলা যেরূপ নিষ্ঠার সাথে পালন করিলেন, তাহাতে রাজার হৃদয় শ্রদ্ধায় পরিপূর্ণ হইল। তিনি স্থির করিলেন, এই আশ্রমকন্যাকেই তিনি আপন মহিষী করিবেন। বিদ্যাসাগর মহাশয়ের এই রচনার মধ্য দিয়া বাংলা গদ্যের যে সাবলীল ও সংগীতময় রূপ ফুটিয়া উঠিয়াছিল, তাহা আমাদের সাহিত্যের ইতিহাসে এক স্বর্ণযুগ সূচনা করিয়াছিল।`,

    // 18
    `আমরা হিন্দু বা মুসলমান যেমন সত্য, তার চেয়ে বেশি সত্য আমরা বাঙালি। এটি কোনো আদর্শের কথা নয়, এটি একটি বাস্তব সত্য। প্রকৃতি নিজের হাতে আমাদের চেহারায় ও ভাষায় এমন ছাপ আঁকিয়া দিয়াছেন যে, তাহা কোনো ধর্মাবরণ দিয়া ঢাকিয়া রাখা যায় না। বাংলা আমাদের মাতৃভাষা, এই ভাষার জন্যই আমাদের অস্তিত্ব। যে জাতি নিজের ভাষাকে সম্মান দিতে জানে না, সে জাতি পৃথিবীতে মাথা উঁচু করিয়া দাঁড়াইতে পারে না। আমাদের দেশে বহু ভাষাভাষীর লোক বাস করিলেও বাংলা ভাষাই সকলের মিলনসূত্র। বিদেশি ভাষা শিক্ষা করা ভালো, কিন্তু নিজের মাতৃভাষাকে বিসর্জন দিয়া নহে। জ্ঞান-বিজ্ঞানের সকল শাখায় বাংলা ভাষার সফল প্রয়োগ নিশ্চিত করিতে হইবে। বিশ্বের বড় বড় জাতিগুলো তাদের নিজের ভাষায় উচ্চশিক্ষা গ্রহণ করিয়া থাকে। বাংলা ভাষা আজ আন্তর্জাতিক মাতৃভাষা দিবসের স্বীকৃতির মাধ্যমে সমগ্র বিশ্বে এক অনন্য মর্যাদায় অধিষ্ঠিত। এখন আমাদের দায়িত্ব হলো এই ভাষাকে জ্ঞান-বিজ্ঞানের সকল শাখায় সমৃদ্ধ করা। বাংলা ভাষার ব্যাকরণ ও বানানের সঠিক চর্চা যদি আমরা অক্ষুণ্ণ রাখিতে পারি, তবে এই ভাষা চিরকাল বিশ্বের শ্রেষ্ঠ ভাষাসমূহের অন্যতম হইয়া বিরাজ করিবে। আমরাও যদি আমাদের মাতৃভাষাকে শিক্ষার প্রধান বাহন করি, তবেই দেশের সর্বস্তরে জ্ঞানের আলো ছড়াইয়া পড়িবে এবং জাতীয় জাগরণ সম্ভব হইবে।`,

    // 19
    `আমার শৈশব কেটেছে মফস্বল শহরে। নদী, বৃষ্টি আর খোলা মাঠ—এই নিয়ে ছিল আমাদের পৃথিবী। বর্ষাকালে যখন মেঘ ডাকত, তখন আমরা ভাইবোনেরা বারান্দায় এসে বসতাম। টিনের চালে বৃষ্টির যে শব্দ হতো, তার চেয়ে মধুর গান আমি জীবনে শুনিনি। নদী ছিল আমাদের পরম বন্ধু। সকালবেলা নদীতে নেমে ঘণ্টার পর ঘণ্টা সাঁতার কাটতাম। বাবা বদলির চাকুরে ছিলেন, তাই এক জায়গায় বেশিদিন থাকার সুযোগ হতো না। কিন্তু যেখানেই যেতাম, প্রকৃতির সাথে এক নতুন মিতালী গড়ে উঠত। মা ছিলেন অদ্ভুত রকমের বইপাগল মানুষ। তিনি হারিকেন জ্বালিয়ে রাতে আমাদের রবীন্দ্রনাথের কবিতা আর শরৎচন্দ্রের উপন্যাস পড়ে শোনাতেন। সেই গল্প শুনতে শুনতে কখন যে ঘুমিয়ে পড়তাম, টেরও পেতাম না। ছোটবেলার সেই বৃষ্টিভেজা বিকেলগুলো, শিউলি ফুলের গন্ধ আর ভাইবোনদের সাথে পুতুল খেলার দিনগুলো আজ কেবলই স্মৃতির পাতায় জমা হয়ে আছে। শহর জীবনের এই কংক্রিটের ভিড়ে দাঁড়িয়ে যখন পেছন ফিরে তাকাই, তখন মনে হয় আমার ছেলেবেলাটি ছিল এক রূপকথার মতো। প্রকৃতির এত কাছে থাকার সুযোগ আজকালকার শিশুরা পায় না। জীবনের সেই সাদামাটা দিনগুলোর কথা মনে পড়লে এখনো মনটা উদাস হয়ে যায়। কোনো কৃত্রিমতা ছিল না, কোনো ব্যস্ততা ছিল না, ছিল শুধু জীবনের নিখাদ আনন্দ।`,

    // 20
    `আজ পঁচিশে মার্চ। চারিদিকে কেমন এক থমথমে নীরবতা। সন্ধ্যার পর থেকেই শুনলাম ক্যান্টনমেন্ট থেকে সৈন্য বের হচ্ছে। একটু পরেই শুরু হলো প্রচণ্ড গুলির আওয়াজ এবং কামানের গর্জন। আকাশটা লাল হয়ে উঠল। আমরা সবাই ঘরের আলো নিভিয়ে খাটের নিচে আশ্রয় নিলাম। আমার বড় ছেলে রুমী জানালার ফাঁক দিয়ে বাইরের দিকে তাকিয়ে ছিল। তার চোখে-মুখে কোনো ভয়ের চিহ্ন দেখলাম না, দেখলাম এক জ্বলন্ত প্রতিজ্ঞা। সে বলল, আম্মা, এভাবে ঘরে বসে থাকা যায় না, আমাদের যুদ্ধে যেতে হবে। মা হয়ে সন্তানকে মৃত্যুর মুখে ঠেলে দেওয়া কত কঠিন, তা কেবল একজন মা-ই জানে। কিন্তু দেশের এই মহাবিপদে আমি রুমীকে বাধা দিতে পারলাম না। তাকে বুকে জড়িয়ে ধরে বললাম, যা বাবা, দেশকে মুক্ত করে ফিরে আয়। যুদ্ধের দিনগুলোতে প্রতিদিন কত মানুষ যে আমাদের বাড়িতে আসত। রুমীর বন্ধুরা অস্ত্র লুকিয়ে রাখত বাগানের মাটির নিচে। আমরা মা-বোনেরা মুক্তিযোদ্ধাদের জন্য ওষুধ, খাবার আর ব্যান্ডেজ জোগাড় করতাম। প্রতি মুহূর্তে মৃত্যুর হাতছানি ছিল, কিন্তু কারো মনে কোনো পিছুটান ছিল না। দেশ স্বাধীন করার সেই তীব্র আকাঙ্ক্ষাই ছিল আমাদের বেঁচে থাকার একমাত্র প্রেরণা। রুমী আর ফিরে আসেনি। কিন্তু তার মতো লাখো তরুণের আত্মত্যাগের বিনিময়েই আজ আমরা স্বাধীন দেশের নাগরিক হতে পেরেছি।`

  ]
};

if (typeof window !== 'undefined') {
  window.PASSAGES = PASSAGES;
}
if (typeof module !== 'undefined') {
  module.exports = PASSAGES;
}
